---
- hosts: all
  tasks:
    - name: Install epel-repo rpm
      yum: name=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm state=present
      sudo: yes
      run_once: true

    - name: Remove Apache
      yum: name=httpd state=absent

    - name: Update the system
      yum: name=* state=latest
      sudo: yes

    - name: Install nano
      yum: name=nano state=present
      sudo: yes

    - name: Ensure node is present
      yum: name={{item}} state=present enablerepo=epel
      with_items:
        - nodejs
        - npm
      sudo: yes

    - name: Ensure nginx is present
      yum: name=nginx state=present enablerepo=epel
      sudo: yes
    - name: Remove unused commands
      command: rm /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/ssl.conf /etc/nginx/conf.d/virtual.conf
      sudo: yes
    - name: Create subsite directory
      command: mkdir /etc/nginx/conf.d/endpoints.d
      sudo: yes
    - name: Copy base nginx config
      command: cp /var/www/xkcd/nginx/default.conf /etc/nginx/conf.d/
      sudo: yes

    - name: Copy xkcd endpoints
      command: cp /var/www/xkcd/nginx/xkcd.conf /etc/nginx/conf.d/endpoints.d/
      sudo: yes
      notify: Start nginx
    # really start nginx should happen after we spin up the node server, but we're not quite there yet

  handlers:
    - name: Start nginx
      service: name=nginx state=started
      sudo: yes
